name:  Deploy

on:
  push:
    branches: [ master, main ]

jobs:

  deploy-testing:
    name: Deploy to test
    environment:
      name: Test
    if: github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy to testing using ${{ secrets.mysecret }}
        
  deploy-staging:
    name: Deploy to dev
    environment:
      name: dev
    if: github.event.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy to staging using ${{ secrets.mysecret }}
        
  deploy-production:
    name: Deploy to production env
    environment:
      name: prod
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy to production using ${{ secrets.mysecret }}
